/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Diver_1: THREE.SkinnedMesh
    Diver_2: THREE.SkinnedMesh
    Diver_3: THREE.SkinnedMesh
    Diver_4: THREE.SkinnedMesh
    Diver_5: THREE.SkinnedMesh
    Diver_6: THREE.SkinnedMesh
    root: THREE.Bone
    ['MCH-torsoparent']: THREE.Bone
    ['MCH-hand_ikparentL']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
    ['MCH-hand_ikparentR']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
    ['MCH-foot_ikparentL']: THREE.Bone
    ['MCH-thigh_ik_targetparentL']: THREE.Bone
    ['MCH-foot_ikparentR']: THREE.Bone
    ['MCH-thigh_ik_targetparentR']: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    traje: THREE.MeshStandardMaterial
    guantes: THREE.MeshStandardMaterial
    mayas: THREE.MeshStandardMaterial
    casco: THREE.MeshStandardMaterial
    detalles: THREE.MeshStandardMaterial
    vidrios: THREE.MeshStandardMaterial
  }
}


export default function Character(props: JSX.IntrinsicElements['group']) {
  const ActionName = 'DiverAction';
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(
    require('../assets/DiverFinalAnimated.glb'),
  ) as GLTFResult

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions[ActionName]?.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Diver">
          <group name="Diver_mesh">
            <skinnedMesh
              name="Diver_1"
              geometry={nodes.Diver_1.geometry}
              material={materials.traje}
              skeleton={nodes.Diver_1.skeleton}
            />
            <skinnedMesh
              name="Diver_2"
              geometry={nodes.Diver_2.geometry}
              material={materials.guantes}
              skeleton={nodes.Diver_2.skeleton}
            />
            <skinnedMesh
              name="Diver_3"
              geometry={nodes.Diver_3.geometry}
              material={materials.mayas}
              skeleton={nodes.Diver_3.skeleton}
            />
            <skinnedMesh
              name="Diver_4"
              geometry={nodes.Diver_4.geometry}
              material={materials.casco}
              skeleton={nodes.Diver_4.skeleton}
            />
            <skinnedMesh
              name="Diver_5"
              geometry={nodes.Diver_5.geometry}
              material={materials.detalles}
              skeleton={nodes.Diver_5.skeleton}
            />
            <skinnedMesh
              name="Diver_6"
              geometry={nodes.Diver_6.geometry}
              material={materials.vidrios}
              skeleton={nodes.Diver_6.skeleton}
            />
          </group>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <group name="WGT-rig_root" scale={0.864} />
        <group
          name="WGT-rig_VIS_upper_arm_ik_poleL"
          rotation={[Math.PI / 2, 0, -1.498]}
          scale={0.428}
        />
        <group
          name="WGT-rig_VIS_upper_arm_ik_poleR"
          rotation={[Math.PI / 2, 0, 1.498]}
          scale={0.428}
        />
        <group
          name="WGT-rig_VIS_thigh_ik_poleL"
          rotation={[Math.PI / 2, 0, -0.111]}
          scale={0.844}
        />
        <group name="WGT-rig_VIS_thigh_ik_poleR" rotation={[Math.PI / 2, 0, 0.111]} scale={0.844} />
        <group name="WGT-rig_torso" scale={0.321} />
        <group name="WGT-rig_hips" rotation={[1.823, 0, 0]} scale={0.134} />
        <group name="WGT-rig_chest" rotation={[1.253, 0, 0]} scale={0.178} />
        <group name="WGT-rig_spine_fk001" rotation={[1.7, 0, 0]} scale={0.111} />
        <group name="WGT-rig_spine_fk" rotation={[1.823, 0, 0]} scale={0.13} />
        <group name="WGT-rig_tweak_spine" rotation={[1.823, 0, 0]} scale={0.065} />
        <group name="WGT-rig_toeL" rotation={[Math.PI, 0, Math.PI]} scale={0.073} />
        <group name="WGT-rig_foot_tweakL" rotation={[-2.656, 0, 0]} scale={0.031} />
        <group name="WGT-rig_shin_tweakL" rotation={[-1.472, 0.033, -0.081]} scale={0.097} />
        <group name="WGT-rig_shin_tweakL001" rotation={[-1.472, 0.033, -0.081]} scale={0.097} />
        <group name="WGT-rig_thigh_tweakL001" rotation={[-1.647, 0.047, -0.074]} scale={0.115} />
        <group name="WGT-rig_toeR" rotation={[-Math.PI, 0, -Math.PI]} scale={0.073} />
        <group name="WGT-rig_foot_tweakR" rotation={[-2.656, 0, 0]} scale={0.031} />
        <group name="WGT-rig_shin_tweakR" rotation={[-1.472, -0.033, 0.081]} scale={0.097} />
        <group name="WGT-rig_shin_tweakR001" rotation={[-1.472, -0.033, 0.081]} scale={0.097} />
        <group name="WGT-rig_thigh_tweakR001" rotation={[-1.647, -0.047, 0.074]} scale={0.115} />
        <group name="WGT-rig_thigh_parentL" rotation={[-1.647, 0.047, 0.05]} scale={0.115} />
        <group name="WGT-rig_thigh_fkL" rotation={[-1.647, 0.047, -0.074]} scale={0.459} />
        <group name="WGT-rig_shin_fkL" rotation={[-1.472, 0.033, -0.081]} scale={0.389} />
        <group name="WGT-rig_foot_fkL" rotation={[-2.656, 0, 0]} scale={0.125} />
        <group name="WGT-rig_thigh_ikL" rotation={[-1.647, 0.047, -0.074]} scale={0.459} />
        <group name="WGT-rig_thigh_tweakL" rotation={[-1.647, 0.047, -0.074]} scale={0.115} />
        <group name="WGT-rig_thigh_parentR" rotation={[-1.647, -0.047, -0.05]} scale={0.115} />
        <group name="WGT-rig_thigh_fkR" rotation={[-1.647, -0.047, 0.074]} scale={0.459} />
        <group name="WGT-rig_shin_fkR" rotation={[-1.472, -0.033, 0.081]} scale={0.389} />
        <group name="WGT-rig_foot_fkR" rotation={[-2.656, 0, 0]} scale={0.125} />
        <group name="WGT-rig_thigh_ikR" rotation={[-1.647, -0.047, 0.074]} scale={0.459} />
        <group name="WGT-rig_thigh_tweakR" rotation={[-1.647, -0.047, 0.074]} scale={0.115} />
        <group name="WGT-rig_tweak_spine001" rotation={[1.7, 0, 0]} scale={0.056} />
        <group name="WGT-rig_spine_fk002" rotation={[1.539, 0, 0]} scale={0.148} />
        <group name="WGT-rig_tweak_spine002" rotation={[1.539, 0, 0]} scale={0.074} />
        <group name="WGT-rig_spine_fk003" rotation={[1.253, 0, 0]} scale={0.145} />
        <group name="WGT-rig_neck" rotation={[1.629, 0, 0]} scale={0.065} />
        <group name="WGT-rig_head" rotation={[Math.PI / 2, 0, 0]} scale={0.237} />
        <group name="WGT-rig_tweak_spine004" rotation={[1.665, 0, 0]} scale={0.014} />
        <group name="WGT-rig_tweak_spine005" rotation={[1.603, 0, -0.011]} scale={0.019} />
        <group name="WGT-rig_tweak_spine003" rotation={[1.253, 0, 0]} scale={0.073} />
        <group name="WGT-rig_hand_tweakL" rotation={[-2.174, -1.394, 2.599]} scale={0.017} />
        <group name="WGT-rig_forearm_tweakL" rotation={[3.105, -1.439, 1.602]} scale={0.047} />
        <group name="WGT-rig_forearm_tweakL001" rotation={[3.105, -1.439, 1.602]} scale={0.047} />
        <group
          name="WGT-rig_upper_arm_tweakL001"
          rotation={[-0.138, -1.512, -1.641]}
          scale={0.06}
        />
        <group name="WGT-rig_upper_arm_parentL" rotation={[-0.138, -1.512, -0.13]} scale={0.06} />
        <group name="WGT-rig_upper_arm_fkL" rotation={[-0.138, -1.512, -1.641]} scale={0.241} />
        <group name="WGT-rig_forearm_fkL" rotation={[3.105, -1.439, 1.602]} scale={0.189} />
        <group name="WGT-rig_hand_fkL" rotation={[-2.174, -1.394, 2.599]} scale={0.069} />
        <group name="WGT-rig_upper_arm_ikL" rotation={[-0.138, -1.512, -1.641]} scale={0.241} />
        <group name="WGT-rig_upper_arm_tweakL" rotation={[-0.138, -1.512, -1.641]} scale={0.06} />
        <group name="WGT-rig_f_index01_masterL" rotation={[-2.315, -1.408, 0.867]} scale={0.141} />
        <group name="WGT-rig_thumb01_masterL" rotation={[-2.711, -0.873, -1.228]} scale={0.157} />
        <group name="WGT-rig_f_index01L" rotation={[-2.315, -1.408, 0.867]} scale={0.04} />
        <group name="WGT-rig_f_index02L" rotation={[-2.036, -1.307, 1.14]} scale={0.021} />
        <group name="WGT-rig_f_index03L" rotation={[-1.935, -1.257, 1.237]} scale={0.022} />
        <group name="WGT-rig_f_index01L001" rotation={[1.206, 1.257, 1.933]} scale={0.011} />
        <group name="WGT-rig_thumb01L" rotation={[-2.711, -0.873, -1.228]} scale={0.037} />
        <group name="WGT-rig_thumb02L" rotation={[-2.61, -0.987, -1.147]} scale={0.032} />
        <group name="WGT-rig_thumb03L" rotation={[-2.448, -1.187, -1.003]} scale={0.027} />
        <group name="WGT-rig_thumb01L001" rotation={[0.693, 1.187, 0.678]} scale={0.013} />
        <group name="WGT-rig_f_middle01_masterL" rotation={[-1.811, -1.389, 1.317]} scale={0.169} />
        <group name="WGT-rig_f_middle01L" rotation={[-1.811, -1.389, 1.317]} scale={0.048} />
        <group name="WGT-rig_f_middle02L" rotation={[-1.751, -1.345, 1.375]} scale={0.027} />
        <group name="WGT-rig_f_middle03L" rotation={[-1.672, -1.162, 1.451]} scale={0.022} />
        <group name="WGT-rig_f_middle01L001" rotation={[1.47, 1.162, 1.636]} scale={0.011} />
        <group name="WGT-rig_f_ring01_masterL" rotation={[-1.333, -1.396, 1.813]} scale={0.146} />
        <group name="WGT-rig_f_ring01L" rotation={[-1.333, -1.396, 1.813]} scale={0.04} />
        <group name="WGT-rig_f_ring02L" rotation={[-1.393, -1.338, 1.754]} scale={0.03} />
        <group name="WGT-rig_f_ring03L" rotation={[-1.473, -1.17, 1.678]} scale={0.015} />
        <group name="WGT-rig_f_ring01L001" rotation={[1.669, 1.17, 1.497]} scale={0.007} />
        <group name="WGT-rig_f_pinky01_masterL" rotation={[-0.973, -1.377, 2.155]} scale={0.116} />
        <group name="WGT-rig_f_pinky01L" rotation={[-0.973, -1.377, 2.155]} scale={0.034} />
        <group name="WGT-rig_f_pinky02L" rotation={[-1.205, -1.262, 1.931]} scale={0.02} />
        <group name="WGT-rig_f_pinky03L" rotation={[-1.303, -1.163, 1.839]} scale={0.012} />
        <group name="WGT-rig_f_pinky01L001" rotation={[1.839, 1.163, 1.345]} scale={0.006} />
        <group name="WGT-rig_palmL" rotation={[-0.497, -1.448, 2.648]} scale={0.057} />
        <group name="WGT-rig_hand_tweakR" rotation={[-2.174, 1.394, -2.599]} scale={0.017} />
        <group name="WGT-rig_forearm_tweakR" rotation={[3.105, 1.439, -1.602]} scale={0.047} />
        <group name="WGT-rig_forearm_tweakR001" rotation={[3.105, 1.439, -1.602]} scale={0.047} />
        <group name="WGT-rig_upper_arm_tweakR001" rotation={[-0.138, 1.512, 1.641]} scale={0.06} />
        <group name="WGT-rig_upper_arm_parentR" rotation={[-0.138, 1.512, 0.13]} scale={0.06} />
        <group name="WGT-rig_upper_arm_fkR" rotation={[-0.138, 1.512, 1.641]} scale={0.241} />
        <group name="WGT-rig_forearm_fkR" rotation={[3.105, 1.439, -1.602]} scale={0.189} />
        <group name="WGT-rig_hand_fkR" rotation={[-2.174, 1.394, -2.599]} scale={0.069} />
        <group name="WGT-rig_upper_arm_ikR" rotation={[-0.138, 1.512, 1.641]} scale={0.241} />
        <group name="WGT-rig_upper_arm_tweakR" rotation={[-0.138, 1.512, 1.641]} scale={0.06} />
        <group name="WGT-rig_f_index01_masterR" rotation={[-2.315, 1.408, -0.867]} scale={0.141} />
        <group name="WGT-rig_thumb01_masterR" rotation={[-2.711, 0.873, 1.228]} scale={0.157} />
        <group name="WGT-rig_f_index01R" rotation={[-2.315, 1.408, -0.867]} scale={0.04} />
        <group name="WGT-rig_f_index02R" rotation={[-2.036, 1.307, -1.14]} scale={0.021} />
        <group name="WGT-rig_f_index03R" rotation={[-1.935, 1.257, -1.237]} scale={0.022} />
        <group name="WGT-rig_f_index01R001" rotation={[1.206, -1.257, -1.933]} scale={0.011} />
        <group name="WGT-rig_thumb01R" rotation={[-2.711, 0.873, 1.228]} scale={0.037} />
        <group name="WGT-rig_thumb02R" rotation={[-2.61, 0.987, 1.147]} scale={0.032} />
        <group name="WGT-rig_thumb03R" rotation={[-2.448, 1.187, 1.003]} scale={0.027} />
        <group name="WGT-rig_thumb01R001" rotation={[0.693, -1.187, -0.678]} scale={0.013} />
        <group name="WGT-rig_f_middle01_masterR" rotation={[-1.811, 1.389, -1.317]} scale={0.169} />
        <group name="WGT-rig_f_middle01R" rotation={[-1.811, 1.389, -1.317]} scale={0.048} />
        <group name="WGT-rig_f_middle02R" rotation={[-1.751, 1.345, -1.375]} scale={0.027} />
        <group name="WGT-rig_f_middle03R" rotation={[-1.672, 1.162, -1.451]} scale={0.022} />
        <group name="WGT-rig_f_middle01R001" rotation={[1.47, -1.162, -1.636]} scale={0.011} />
        <group name="WGT-rig_f_ring01_masterR" rotation={[-1.333, 1.396, -1.813]} scale={0.146} />
        <group name="WGT-rig_f_ring01R" rotation={[-1.333, 1.396, -1.813]} scale={0.04} />
        <group name="WGT-rig_f_ring02R" rotation={[-1.393, 1.338, -1.754]} scale={0.03} />
        <group name="WGT-rig_f_ring03R" rotation={[-1.473, 1.17, -1.678]} scale={0.015} />
        <group name="WGT-rig_f_ring01R001" rotation={[1.669, -1.17, -1.497]} scale={0.007} />
        <group name="WGT-rig_f_pinky01_masterR" rotation={[-0.973, 1.377, -2.155]} scale={0.116} />
        <group name="WGT-rig_f_pinky01R" rotation={[-0.973, 1.377, -2.155]} scale={0.034} />
        <group name="WGT-rig_f_pinky02R" rotation={[-1.205, 1.262, -1.931]} scale={0.02} />
        <group name="WGT-rig_f_pinky03R" rotation={[-1.303, 1.163, -1.839]} scale={0.012} />
        <group name="WGT-rig_f_pinky01R001" rotation={[1.839, -1.163, -1.345]} scale={0.006} />
        <group name="WGT-rig_palmR" rotation={[-0.497, 1.448, -2.648]} scale={0.057} />
        <group name="WGT-rig_shoulderL" rotation={[-0.001, -0.816, -0.001]} scale={0.124} />
        <group name="WGT-rig_shoulderR" rotation={[-0.001, 0.816, 0.001]} scale={0.124} />
        <group name="WGT-rig_hand_ikL" rotation={[-2.174, -1.394, 2.599]} scale={0.069} />
        <group
          name="WGT-rig_upper_arm_ik_targetL"
          rotation={[3.074, 0.025, -0.702]}
          scale={0.054}
        />
        <group name="WGT-rig_hand_ikR" rotation={[-2.174, 1.394, -2.599]} scale={0.069} />
        <group
          name="WGT-rig_upper_arm_ik_targetR"
          rotation={[3.074, -0.025, 0.702]}
          scale={0.054}
        />
        <group name="WGT-rig_foot_ikL" scale={0.125} />
        <group name="WGT-rig_foot_spin_ikL" scale={0.063} />
        <group name="WGT-rig_foot_heel_ikL" scale={0.063} />
        <group name="WGT-rig_thigh_ik_targetL" rotation={[0.001, -0.077, 0]} scale={0.106} />
        <group name="WGT-rig_foot_ikR" scale={0.125} />
        <group name="WGT-rig_foot_spin_ikR" scale={0.063} />
        <group name="WGT-rig_foot_heel_ikR" scale={0.063} />
        <group name="WGT-rig_thigh_ik_targetR" rotation={[0.001, 0.077, 0]} scale={0.106} />
      </group>
    </group>
  )
}

//useGLTF.preload('/DiverFinalAnimated.glb')
